# Generated by Django 2.2.19 on 2023-04-21 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_auto_20230420_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chieldmenu',
            name='father_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_name', to='trees.Menu', verbose_name='Отец'),
        ),
    ]
